# Default config values
[config]
format = "{&output}"
compact = false
no_color = false
strict = false

# Default variables
[variables]
output    = "{#key timestamp|level|lvl|severity|message|msg|body|fields.message}{&timestamp}{&level}{&message}{#config compact} {:else}\\n{/config}{/key}{&data}"
timestamp = "{#key timestamp}{timestamp:dimmed} {/key}"
level     = "{#key level|lvl|severity}{level|lvl|severity:level} {/key}"
message   = "{message|msg|body|fields.message}"
data      = "{..:json}"
