# Default config values
[config]
format = "{&output}"
compact = false
no_color = false
strict = false

# Default variables
[variables]
output = "{#key &log}{&log_fmt}{&new_line}{/key}{&data_fmt}"
log = "{&timestamp|&level|&message}"
log_fmt = "{&timestamp_fmt}{&level_fmt}{&message_fmt}"
timestamp_fmt = "{#key &timestamp}{&timestamp:dimmed} {/key}"
timestamp = "{timestamp}"
level_fmt = "{#key &level}{&level:level} {/key}"
level = "{level|lvl|severity}"
message_fmt = "{&message}"
message = "{message|msg|body|fields.message}"
new_line = "{#key &data}{#config compact} {:else}\\n{/config}{/key}"
data_fmt = "{&data:json}"
data = "{..}"
