[package]
name = "json-logger"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
name = "json_logger"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bumpalo = { version = "3.14.0", features = ["std"] }
clap = { version = "4.4.18", features = ["derive"] }
owo-colors = { version = "4.0.0", features = ["alloc", "supports-colors"] }
smallvec = { version = "1.13.1", features = ["const_generics"] }

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }
serde = "1.0.196"
serde_json = "1.0.113"

[[bench]]
name = "parse_json"
harness = false
